name: NodeJS c8 coverage on CI to Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: latest
      run: npm i -G c8
      run: npm run ci
    - name: Upload to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.lcov
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
