name: NodeJS CI Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup NodeJS
      uses: actions/setup-node@master
      with:
        node-version: '14.16.0'
    - name: Install dependencies
      run: yarn
    - name: Generate coverage
      run: yarn c8-text-lcov
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.lcov
        name: codecov-umbrella
        fail_ci_if_error: true
